apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepskyn-frontend
  labels:
    app: deepskyn-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deepskyn-frontend
  template:
    metadata:
      labels:
        app: deepskyn-frontend
    spec:
      containers:
      - name: deepskyn-frontend
        image: your-docker-registry/deepskyn-frontend:TAG_VERSION
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deepskyn-frontend-service
spec:
  selector:
    app: deepskyn-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
